spring:
  mail:
    host: ${HOST}
    port: ${PORT}
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
