spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mostafadfrg@gmail.com
    password: qzbcgpgalkqvipki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
